spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yelp_recommendation_system
  datasource:
    driver-class-name:
server:
  port: 8082
ann:
  pathToSave: C:/ann/4-8-8.ann