spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: yelp_recommendation_system
  datasource:
    driver-class-name:
server:
  port: 8082
ann:
  pathToSave: C:/ann/2019-01-11-v3.ann

logging:
  level:
    org.springframeworkdata.mongodb.core.MongoTempalte: DEBUG